name: SkyBlockSimulation
version: 1.0
author: IchMagOmasKekse
version: 0.1

load: startup

main: me.ichmagomaskekse.de.SkyBlock
commands:
  simulate:
    description: 'Start a skyblock raster simulation'
  undo:
    description: 'Undo all Simulations'