name: SkyBlockSimulation
author: TeamDream
version: 1.0.0
api-version: 1.16
main: me.dreamisland.de.SkyBlock
commands:
  simulate:
    description: 'Start a skyblock raster simulation'
  undo:
    description: 'Undo all Simulations'
  is:
    description: 'Maincommand for Skyblock'
    aliases: [skyblock, sb, sky, island, islands]
  spawn:
    description: 'Teleports you to spawn'
    aliases: [hub, leave, lounge, lobby]
  accept:
    description: 'Accept a outstanding request'
  deny:
    description: 'Deny a outstanding request'
  s:
    description: 'Maincommand for Schematic-System'
    aliases: [schem, schematic]
  loaditem:
    description: 'Load an item from item preset file'
  saveitem:
    decription: 'Save an item to preset file'