name: SkyBlock
author: TeamSkytale
version: 1.5.4
api-version: 1.16
main: me.skytale.de.SkyBlock
commands:
  simulate:
    description: 'Start a skyblock raster simulation'
  undo:
    description: 'Undo all Simulations'
  is:
    description: 'Maincommand for Skyblock'
    aliases: [skyblock, sb, sky, island, islands]
  accept:
    description: 'Accept a outstanding request'
  deny:
    description: 'Deny a outstanding request'
  s:
    description: 'Maincommand for Schematic-System'
    aliases: [schem, schematic]
  loaditem:
    description: 'Load an item from item preset file'
  saveitem:
    description: 'Save an item to preset file'
  claimed:
    description: 'List all claimed Islands'
  unclaimed:
    description: 'List all unclaimed Islands'
  release:
    description: 'Release an Island to be able to get claimed again'
  coins:
    description: 'SkyCoins Maincommand'
  dailyreward:
    description: 'Get your daily reward'
  gui:
    description: 'Open a GUI'
  help:
    description: 'Get a list of all for you available commands and some useful help on top'
  broadcaster:
    description: 'Main command for the broadcaster'
    aliases: [bc, bcaster, rundruf]
permissions:
  skyblock.*:
    description: All permissions for the SkyBlock plugin
    children:
      skyblock.admin: true
      skyblock.adminhelp: true
      skyblock.commandhelp: true
      skyblock.unclaimed: true
      skyblock.claimed: true
      skyblock.chat.color: true
      skyblock.coins.other: true
      skyblock.coins: true
      skyblock.simulate: true
      skyblock.undo: true
      skyblock.release: true
      skyblock.island.reloadcobble: true
      skyblock.island: true
      skyblock.island.help: true
      skyblock.island.setspawn: true
      skyblock.island.cown: true
      skyblock.island.create: true
      skyblock.island.ban: true
      skyblock.island.pardon: true
      skyblock.island.delworld: true
      skyblock.island.delete: true
      skyblock.island.kick: true
      skyblock.island.addfriend: true
      skyblock.island.delfriend: true
      skyblock.island.friends: true
      skyblock.island.tp: true
      skyblock.island.spy: true
      skyblock.island.visit: true
      skyblock.island.gamemode.bypass: true
      skyblock.modify.islands: true
      skyblock.interact.entity: true
      skyblock.coins: true
      skyblock.dailyreward: true
      skyblock.gui: true
      skyblock.broadcaster: true
  skyblock.admin:
    description: You cannot get kicked off of a Island by a player if you have this permission
    skyblock.adminhelp:
    description: See admin help for various admin processes
  skyblock.commandhelp:
    description: See help for all alvailable commands which you can use
  skyblock.release:
    description: Release an deleted Island
  skyblock.unclaimed:
    description: See all unclaimed Islands
  skyblock.claimed:
    description: See all claimed Islands
  skyblock.chat.color:
    description: Use colors in chat messages
  skyblock.simulate:
    description: HEAVY IMPACT TO SERVER PERFORMANCE! ONLY ARIANO IS ALLOWED TO IS THIS!
  skyblock.undo:
    description: Undo a simulation
  skyblock.island.reloadcobble:
    description: Reload the Cobblestone Generator settings file
  skyblock.island:
    description: Use the main Island command
  skyblock.island.help:
    description: See help for the island command
  skyblock.island.setspawn:
    description: Set a new player spawn for your island
  skyblock.island.cown:
    description: Create your own Island, if you are membered on another one
  skyblock.island.create:
    description: Create your own Island, if you are not having one yet
  skyblock.island.ban:
    description: Ban a player from your Island
  skyblock.island.pardon:
    description: Undo a ban
  skyblock.island.delworld:
    description: ONLY ARIANO IS ALLOWED TO USE THIS! Delete the SkyBlockWorld
  skyblock.island.delete:
    description: Delete your Island
  skyblock.island.kick:
    description: Kick a player off of your Island
  skyblock.island.addfriend:
    description: Add a player to your Island to play together
  skyblock.island.delfriend:
    description: Delete a player from your Island
  skyblock.island.friends:
    description: See all your friends you have added to your Island
  skyblock.island.tp:
    description: Teleport to a Island
  skyblock.island.spy:
    description: Spectate a Island for admin purposes for example
  skyblock.island.visit:
    description: Visit an Island of another Player
  skyblock.island.gamemode.bypass:
    description: Keep your GameMode after you have created a Island
  skyblock.modify.islands:
    description: Place and break blocks on other Islands
  skyblock.interact.entity:
    description: Interact with entities on other Islands
  skyblock.coins:
    description: Show your SkyCoins
  skyblock.coins.other:
    description: Show SkyCoins of another player
  skyblock.dailyreward:
    description: Get your daily reward
  skyblock.gui:
    description: Open a gui
  skyblock.broadcaster:
    description: Prepare the broadcaster