name: SkyBlockSimulation
author: TeamDream
version: 0.1

load: STARTUP

main: me.ichmagomaskekse.de.SkyBlock
commands:
  simulate:
    description: 'Start a skyblock raster simulation'
  undo:
    description: 'Undo all Simulations'
  is:
    description: 'Maincommand for Skyblock'
    aliases: [skyblock, sb, sky, island, islands]